api: 
  url: https://eval.contrastsecurity.com/Contrast
  api_key: 7XYyxPHNsvfyqyH03Pv780Bg3MpAxlaF
  service_key: Z86G9V477K9K6TKH
  user_name: agent_77669368-0741-4f3d-80ad-26cdb7e14a99@Rstatsinger
agent: 
  logger:
   path: /tmp/contrastagent.log
   level: ERROR
  service: 
    logger: 
      path: /tmp/contrastservice.log
      level: ERROR
    host: 127.0.0.1
    port: 30555
assess:
 enable: true
